### ISSUE TITLE
Redesign: TODO

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client-aiortc#5]
Working on "v3" branch. Missing stuff:

* [x] Proper and updated `README.md`.
* [x] Unit tests (those may mimic the ones in mediasoup-client project).
* [x] Implement `producer.replaceTrack()`.
* [x] Wait for a new version of `aiortc` including the fix for the "Tons of keyframes after receiving a PLI" [issue](https://github.com/aiortc/aiortc/issues/275).
* [x] Wait for `aiortc` to merge this [PR](https://github.com/aiortc/aiortc/pull/292) about zombie Python process.
* [x] Wait for `aiortc` to release this [fix](https://github.com/aiortc/aiortc/pull/287).

**Comment by ibc** [comment]
Done.
