### ISSUE TITLE
aiortc TODO

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client-aiortc#9]
Being done in the `devel` branch until we have a new `aiortc` release with:

* [x] Missing receiver.track property: [issue 298](https://github.com/aiortc/aiortc/issues/298)
* [x] player.video.stop() never returns if called after player.audio.stop(): [issue 301](https://github.com/aiortc/aiortc/issues/301)
  - Let's forget this, it makes no sense (a simple `console.log()` in the unit test makes it always work...)
* [ ] Allow same track to be sent N times: [issue 302](https://github.com/aiortc/aiortc/issues/302)
* [x] Strange `trackId` value in stats: [issue 303](https://github.com/aiortc/aiortc/issues/303)
* [ ] `sender.replaceTrack()`: strange behavior (frozen video for N seconds): [issue 304](https://github.com/aiortc/aiortc/issues/304)
  - Known issue. Related: https://github.com/aiortc/aiortc/issues/228
* [x] Make it possible to send a recv `track` (feasible in `aiortc`). So we need to check `track.data.remote === true` in `handler.send()` or `handler.replaceTrack()` and match `track.id` in handler.py against existing recv native tracks.

**Comment by jymot** [comment]
Can we see the devel branch?

**Comment by jmillan** [comment]
> Can we see the devel branch?

There is no such branch anymore. Refer to v3 for the current code.

**Comment by jymot** [comment]
> Make it possible to send a recv track (feasible in aiortc). So we need to check track.data.remote === true in handler.send() or handler.replaceTrack() and match track.id in handler.py against existing recv native tracks.

Is this function not implemented yet? It seems that I can only look at our code and research it myself.
@jmillan

**Comment by jmillan** [comment]
Commented in [mediasoup.discourse.group](https://mediasoup.discourse.group/t/can-i-pass-the-consume-track-to-another-mediasoup/660/2)
